micronaut:
  application:
    name: micronautServer
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          jwks:
            auth0:
              url: 'https://access-me.eu.auth0.com/.well-known/jwks.json'
            okta:
              url: 'https://dev-667216.oktapreview.com/oauth2/ausjbx4pq5Wg0kZx10h7/v1/keys'
netty:
  default:
    allocator:
      max-order: 3
